# Generated by Django 5.0.1 on 2024-03-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='location',
        ),
    ]
