# Generated by Django 5.0.1 on 2024-03-02 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_remove_donor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1), null=True),
        ),
    ]
