# Generated by Django 5.0.1 on 2024-02-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/img/bloodbank/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100)),
                ('units', models.IntegerField(default=1)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bloodbank')),
            ],
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
    ]
