# Generated by Django 5.0.1 on 2024-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
